[package]
name = "apple_products_parser"
version = "0.1.0"
edition = "2021"
description = "A tool that processes detailed data about Apple products(Iphones, MacBooks and IPads)"


[dependencies]
pest = "2.7.14"
pest_derive = "2.7.14"
anyhow = "1.0"